import crypto from "crypto";
import { config } from "./config";

const ALGORITHM = "aes-256-gcm";

// Derive a 32-byte key from MASTER_KEY via SHA-256 so any sufficiently random string works
// (e.g. secrets auto-generated by a hosting provider), not just a 64-char hex value.
function masterKeyBuffer(): Buffer {
  return crypto.createHash("sha256").update(config.masterKey).digest();
}

// Output format: iv(hex):authTag(hex):ciphertext(hex)
export function encryptSecret(plaintext: string): string {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ALGORITHM, masterKeyBuffer(), iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return `${iv.toString("hex")}:${authTag.toString("hex")}:${ciphertext.toString("hex")}`;
}

export function decryptSecret(payload: string): string {
  const [ivHex, authTagHex, ciphertextHex] = payload.split(":");
  if (!ivHex || !authTagHex || !ciphertextHex) {
    throw new Error("Malformed encrypted secret payload");
  }
  const decipher = crypto.createDecipheriv(
    ALGORITHM,
    masterKeyBuffer(),
    Buffer.from(ivHex, "hex")
  );
  decipher.setAuthTag(Buffer.from(authTagHex, "hex"));
  const plaintext = Buffer.concat([
    decipher.update(Buffer.from(ciphertextHex, "hex")),
    decipher.final(),
  ]);
  return plaintext.toString("utf8");
}

export function maskKey(plaintext: string): string {
  if (plaintext.length <= 8) return "****";
  return `${plaintext.slice(0, 4)}${"*".repeat(8)}${plaintext.slice(-4)}`;
}
